// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/github/aaronai/hello.proto

package io.github.aaronai.proto;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SayHelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.aaronai.proto.SayHelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string request_content = 1;</code>
     * @return The requestContent.
     */
    java.lang.String getRequestContent();
    /**
     * <code>string request_content = 1;</code>
     * @return The bytes for requestContent.
     */
    com.google.protobuf.ByteString
        getRequestContentBytes();
  }
  /**
   * Protobuf type {@code io.github.aaronai.proto.SayHelloRequest}
   */
  public static final class SayHelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.aaronai.proto.SayHelloRequest)
      SayHelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SayHelloRequest.newBuilder() to construct.
    private SayHelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SayHelloRequest() {
      requestContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SayHelloRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SayHelloRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestContent_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.aaronai.proto.Hello.SayHelloRequest.class, io.github.aaronai.proto.Hello.SayHelloRequest.Builder.class);
    }

    public static final int REQUEST_CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestContent_;
    /**
     * <code>string request_content = 1;</code>
     * @return The requestContent.
     */
    @java.lang.Override
    public java.lang.String getRequestContent() {
      java.lang.Object ref = requestContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestContent_ = s;
        return s;
      }
    }
    /**
     * <code>string request_content = 1;</code>
     * @return The bytes for requestContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestContentBytes() {
      java.lang.Object ref = requestContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestContent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestContent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.aaronai.proto.Hello.SayHelloRequest)) {
        return super.equals(obj);
      }
      io.github.aaronai.proto.Hello.SayHelloRequest other = (io.github.aaronai.proto.Hello.SayHelloRequest) obj;

      if (!getRequestContent()
          .equals(other.getRequestContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getRequestContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.Hello.SayHelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.aaronai.proto.Hello.SayHelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.aaronai.proto.SayHelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.aaronai.proto.SayHelloRequest)
        io.github.aaronai.proto.Hello.SayHelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.aaronai.proto.Hello.SayHelloRequest.class, io.github.aaronai.proto.Hello.SayHelloRequest.Builder.class);
      }

      // Construct using io.github.aaronai.proto.Hello.SayHelloRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestContent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
      }

      @java.lang.Override
      public io.github.aaronai.proto.Hello.SayHelloRequest getDefaultInstanceForType() {
        return io.github.aaronai.proto.Hello.SayHelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.aaronai.proto.Hello.SayHelloRequest build() {
        io.github.aaronai.proto.Hello.SayHelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.aaronai.proto.Hello.SayHelloRequest buildPartial() {
        io.github.aaronai.proto.Hello.SayHelloRequest result = new io.github.aaronai.proto.Hello.SayHelloRequest(this);
        result.requestContent_ = requestContent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.aaronai.proto.Hello.SayHelloRequest) {
          return mergeFrom((io.github.aaronai.proto.Hello.SayHelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.aaronai.proto.Hello.SayHelloRequest other) {
        if (other == io.github.aaronai.proto.Hello.SayHelloRequest.getDefaultInstance()) return this;
        if (!other.getRequestContent().isEmpty()) {
          requestContent_ = other.requestContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.aaronai.proto.Hello.SayHelloRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.aaronai.proto.Hello.SayHelloRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestContent_ = "";
      /**
       * <code>string request_content = 1;</code>
       * @return The requestContent.
       */
      public java.lang.String getRequestContent() {
        java.lang.Object ref = requestContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string request_content = 1;</code>
       * @return The bytes for requestContent.
       */
      public com.google.protobuf.ByteString
          getRequestContentBytes() {
        java.lang.Object ref = requestContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string request_content = 1;</code>
       * @param value The requestContent to set.
       * @return This builder for chaining.
       */
      public Builder setRequestContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string request_content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestContent() {
        
        requestContent_ = getDefaultInstance().getRequestContent();
        onChanged();
        return this;
      }
      /**
       * <code>string request_content = 1;</code>
       * @param value The bytes for requestContent to set.
       * @return This builder for chaining.
       */
      public Builder setRequestContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestContent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.aaronai.proto.SayHelloRequest)
    }

    // @@protoc_insertion_point(class_scope:io.github.aaronai.proto.SayHelloRequest)
    private static final io.github.aaronai.proto.Hello.SayHelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.aaronai.proto.Hello.SayHelloRequest();
    }

    public static io.github.aaronai.proto.Hello.SayHelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SayHelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<SayHelloRequest>() {
      @java.lang.Override
      public SayHelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SayHelloRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SayHelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SayHelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.aaronai.proto.Hello.SayHelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SayHelloResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.aaronai.proto.SayHelloResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response_content = 1;</code>
     * @return The responseContent.
     */
    java.lang.String getResponseContent();
    /**
     * <code>string response_content = 1;</code>
     * @return The bytes for responseContent.
     */
    com.google.protobuf.ByteString
        getResponseContentBytes();
  }
  /**
   * Protobuf type {@code io.github.aaronai.proto.SayHelloResponse}
   */
  public static final class SayHelloResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.aaronai.proto.SayHelloResponse)
      SayHelloResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SayHelloResponse.newBuilder() to construct.
    private SayHelloResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SayHelloResponse() {
      responseContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SayHelloResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SayHelloResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseContent_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.aaronai.proto.Hello.SayHelloResponse.class, io.github.aaronai.proto.Hello.SayHelloResponse.Builder.class);
    }

    public static final int RESPONSE_CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseContent_;
    /**
     * <code>string response_content = 1;</code>
     * @return The responseContent.
     */
    @java.lang.Override
    public java.lang.String getResponseContent() {
      java.lang.Object ref = responseContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseContent_ = s;
        return s;
      }
    }
    /**
     * <code>string response_content = 1;</code>
     * @return The bytes for responseContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseContentBytes() {
      java.lang.Object ref = responseContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseContent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseContent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.aaronai.proto.Hello.SayHelloResponse)) {
        return super.equals(obj);
      }
      io.github.aaronai.proto.Hello.SayHelloResponse other = (io.github.aaronai.proto.Hello.SayHelloResponse) obj;

      if (!getResponseContent()
          .equals(other.getResponseContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getResponseContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.Hello.SayHelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.aaronai.proto.Hello.SayHelloResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.aaronai.proto.SayHelloResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.aaronai.proto.SayHelloResponse)
        io.github.aaronai.proto.Hello.SayHelloResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.aaronai.proto.Hello.SayHelloResponse.class, io.github.aaronai.proto.Hello.SayHelloResponse.Builder.class);
      }

      // Construct using io.github.aaronai.proto.Hello.SayHelloResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseContent_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.aaronai.proto.Hello.internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
      }

      @java.lang.Override
      public io.github.aaronai.proto.Hello.SayHelloResponse getDefaultInstanceForType() {
        return io.github.aaronai.proto.Hello.SayHelloResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.aaronai.proto.Hello.SayHelloResponse build() {
        io.github.aaronai.proto.Hello.SayHelloResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.aaronai.proto.Hello.SayHelloResponse buildPartial() {
        io.github.aaronai.proto.Hello.SayHelloResponse result = new io.github.aaronai.proto.Hello.SayHelloResponse(this);
        result.responseContent_ = responseContent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.aaronai.proto.Hello.SayHelloResponse) {
          return mergeFrom((io.github.aaronai.proto.Hello.SayHelloResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.aaronai.proto.Hello.SayHelloResponse other) {
        if (other == io.github.aaronai.proto.Hello.SayHelloResponse.getDefaultInstance()) return this;
        if (!other.getResponseContent().isEmpty()) {
          responseContent_ = other.responseContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.aaronai.proto.Hello.SayHelloResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.aaronai.proto.Hello.SayHelloResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseContent_ = "";
      /**
       * <code>string response_content = 1;</code>
       * @return The responseContent.
       */
      public java.lang.String getResponseContent() {
        java.lang.Object ref = responseContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response_content = 1;</code>
       * @return The bytes for responseContent.
       */
      public com.google.protobuf.ByteString
          getResponseContentBytes() {
        java.lang.Object ref = responseContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_content = 1;</code>
       * @param value The responseContent to set.
       * @return This builder for chaining.
       */
      public Builder setResponseContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response_content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseContent() {
        
        responseContent_ = getDefaultInstance().getResponseContent();
        onChanged();
        return this;
      }
      /**
       * <code>string response_content = 1;</code>
       * @param value The bytes for responseContent to set.
       * @return This builder for chaining.
       */
      public Builder setResponseContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseContent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.aaronai.proto.SayHelloResponse)
    }

    // @@protoc_insertion_point(class_scope:io.github.aaronai.proto.SayHelloResponse)
    private static final io.github.aaronai.proto.Hello.SayHelloResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.aaronai.proto.Hello.SayHelloResponse();
    }

    public static io.github.aaronai.proto.Hello.SayHelloResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SayHelloResponse>
        PARSER = new com.google.protobuf.AbstractParser<SayHelloResponse>() {
      @java.lang.Override
      public SayHelloResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SayHelloResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SayHelloResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SayHelloResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.aaronai.proto.Hello.SayHelloResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035io/github/aaronai/hello.proto\022\027io.gith" +
      "ub.aaronai.proto\"*\n\017SayHelloRequest\022\027\n\017r" +
      "equest_content\030\001 \001(\t\",\n\020SayHelloResponse" +
      "\022\030\n\020response_content\030\001 \001(\t2\334\001\n\010SayHello\022" +
      "^\n\005Unary\022(.io.github.aaronai.proto.SayHe" +
      "lloRequest\032).io.github.aaronai.proto.Say" +
      "HelloResponse\"\000\022p\n\023BidirectionalStream\022(" +
      ".io.github.aaronai.proto.SayHelloRequest" +
      "\032).io.github.aaronai.proto.SayHelloRespo" +
      "nse\"\000(\0010\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor,
        new java.lang.String[] { "RequestContent", });
    internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor,
        new java.lang.String[] { "ResponseContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
